#pragma kernel Sharpen

RWStructuredBuffer<float4> colors;

int resX, resY;

int i;
int l, r, b, t;

int lI, rI, bI, tI;
int bLI, bRI, tLI, tRI;

int IndexOf(int x, int y)
{
    if (x >= resX)
        return -1;
    
    if (y >= resY)
        return -1;
    
    return y * resY + x;
}

[numthreads(32, 32, 1)]
void Sharpen(uint3 id : SV_DispatchThreadID)
{
    i = IndexOf(id.x, id.y);

    l = id.x - 1;
    r = id.x + 1;
    b = id.y - 1;
    t = id.y + 1;

    l = l < 0 ? 1 : l;
    r = r >= resX ? resX - 1 : r;
    b = b < 0 ? 1 : b;
    t = t >= resY ? resY - 1 : t;
    
    lI = id.y * resY + l;
    rI = id.y * resY + r;
    bI = b * resY + id.x;
    tI = t * resY + id.x;
    bLI = b * resY + l;
    bRI = b * resY + r;
    tLI = t * resY + l;
    tRI = t * resY + r;
    
    colors[i].x = 2.0f * colors[i].x - ((colors[i].x + colors[lI].x + colors[rI].x + colors[bI].x + colors[tI].x + colors[bLI].x + colors[bRI].x + colors[tLI].x + colors[tRI].x) / 9.0f);
    colors[i].y = 2.0f * colors[i].y - ((colors[i].y + colors[lI].y + colors[rI].y + colors[bI].y + colors[tI].y + colors[bLI].y + colors[bRI].y + colors[tLI].y + colors[tRI].y) / 9.0f);
    colors[i].z = 2.0f * colors[i].z - ((colors[i].z + colors[lI].z + colors[rI].z + colors[bI].z + colors[tI].z + colors[bLI].z + colors[bRI].z + colors[tLI].z + colors[tRI].z) / 9.0f);
    colors[i].w = 1.0f;
}